spring.application.name=inventory-service

server.port=8081

# postgresql datasource
#spring.datasource.url=jdbc:postgresql://localhost:55000/localdb?currentSchema=inventory_system
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username= postgres
#spring.datasource.password= postgrespw

#h2 datasource
spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Always run SQL scripts
spring.sql.init.mode=never

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/inventory-service/swagger-ui